// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IRateLimitsModel {
    allowed_calls_per_month: string;
    remaining_calls_per_month: string;
    allowed_calls_per_minute: string;
    remaining_calls_per_minute: string;
}
